//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Raviz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileNo
    {
        public int Id { get; set; }
        public int RecordId { get; set; }
        public string Numbers { get; set; }
        public string Validity { get; set; }
    
        public virtual RecordData RecordData { get; set; }
    }
}
