//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Raviz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordData
    {
        public int Id { get; set; }
        public string AccountNo { get; set; }
        public string CustomerName { get; set; }
        public string BCheque { get; set; }
        public string BCheque_P { get; set; }
        public string IPTelephone_Billing { get; set; }
        public string Utility_Billing { get; set; }
        public string Others { get; set; }
        public string OS_Billing { get; set; }
        public string License_expiry { get; set; }
        public string Contact_Person { get; set; }
        public string Nationality { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Mobile3 { get; set; }
        public string Mobile4 { get; set; }
        public string Email_1 { get; set; }
        public string Email_2 { get; set; }
        public string Email_3 { get; set; }
        public string Disposition { get; set; }
        public string SubDisposition { get; set; }
        public string Comments { get; set; }
        public string ChangeStatus { get; set; }
    }
}
