//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Raviz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_4
    {
        public int CUSTOMER_CODE { get; set; }
        public string ageing { get; set; }
        public string Segment { get; set; }
        public string Agency_name { get; set; }
        public Nullable<System.DateTime> PMT_DT { get; set; }
        public Nullable<double> pmt_amt { get; set; }
    }
}
